Coreected a logical error in new exit on error logic

diff --git a/install b/install
--- a/install
+++ b/install
@@ -51,15 +51,15 @@ if [ -d "$2" ]; then
     tar --strip-components=1 -x"$VTAR"f  tars/"$TOOL".tar.bz2 -C "$2"/crosstools/"$1"/crosscompiler/"$TOOL" || (echo "Error while untarring tools" && exit 1)
 
     echo "Copying Executables"
-    for y in $(for x in $bins; do which $x; done); do (mkdir -p "$2"/crosstools/"$1""`dirname $y`" && cp $VCP $y "$2"/crosstools/"$1""`dirname $y`") || (echo "Error while copying an executable" && exit 1); done
+    for y in $(for x in $bins; do which $x; done); do (mkdir -p "$2"/crosstools/"$1""`dirname $y`" || (echo "Error while creating Directory" && exit 1)) && (cp $VCP $y "$2"/crosstools/"$1""`dirname $y`" || (echo "Error while copying an executable" && exit 1)); done
     
     echo "Copying Libs"
-    CROSS_TOOLS="$2"/crosstools/"$1"/crosscompiler/"$TOOL"/bin
+    CROSS_TOOLS_BIN="$2"/crosstools/"$1"/crosscompiler/"$TOOL"/bin
     for x in $bins; do allbins+="$(which $x) "; done
-    for x in $(ls -ltr "$CROSS_TOOLS"/* | awk {'print $9'}); do allbins+="$x "; done
+    for x in $(ls -ltr "$CROSS_TOOLS_BIN"/* | awk {'print $9'}); do allbins+="$x "; done
     for y in $(for x in $allbins; do ldd $x; done| grep "=>" | awk {'print $3'} | uniq); do libs+="$y ";done
     for y in $(for x in $allbins; do ldd $x; done | grep -v "=>" | grep -i "/lib" | awk {'print $1'}|uniq); do libs+="$y ";done
-    for x in $libs; do (mkdir -p "$2"/crosstools/"$1""`dirname $x`" && cp $VCP $x "$2"/crosstools/"$1""`dirname $x`") || (echo "Error while Copying a LIbrary" && exit 1);done
+    for x in $libs; do (mkdir -p "$2"/crosstools/"$1""`dirname $x`" || (echo "Error while creating Directory" && exit 1)) && (cp $VCP $x "$2"/crosstools/"$1""`dirname $x`" || (echo "Error while Copying a LIbrary" && exit 1));done
 else	
     echo "Path " $2 " doesnot exist"
     exit 1
